Update Actions to handle multiple commits

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -11,34 +11,35 @@ on:
 
 jobs:
   build:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-22.04
 
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
         with:
-          fetch-depth: 2
+          fetch-depth: 0
 
       - name: Install Clang
-        run: sudo apt-get install -y clang
+        run: apt-get update && apt-get install -y git
 
-      - name: Test C++ file
-        id: git-diff
+      - name: Test C++ files
         run: |
-          problem=$(git diff --name-only --diff-filter=AM HEAD^1...HEAD | grep '.cpp' | sed 's/.cpp//g' | xargs)
-          echo $(git diff --name-only --diff-filter=AM HEAD^1...HEAD)
-          if [[ -n "$problem" ]]; then
-            clang++ -std=c++20 -fsanitize=address -o "$problem" "$problem".cpp
-            result=$(python3 test.py $problem)
-            echo "$result"
-            if [[ $result == "FAIL" ]]; then
-              echo "Tests failed"
-              exit 1
+          for commit in $(git rev-list ${{ github.base_ref }}..${{ github.head_ref }}); do
+            problem=$(git diff --name-only --diff-filter=AM $commit^1...$commit | grep '.cpp' | sed 's/.cpp//g' | xargs)
+            echo $(git diff --name-only --diff-filter=AM HEAD^1...HEAD)
+            if [[ -n "$problem" ]]; then
+              clang++ -std=c++20 -fsanitize=address -o "$problem" "$problem".cpp
+              result=$(python3 test.py $problem)
+              echo "$result"
+              if [[ $result == "FAIL" ]]; then
+                echo "Tests failed"
+                exit 1
+              else
+                echo "All tests passed"
+              fi
             else
-              echo "All tests passed"
+              # Success github actions early
+              echo "No C++ file modified"
+              exit 0
             fi
-          else
-            # Success github actions early
-            echo "No C++ file modified"
-            exit 0
-          fi
+          done
